### ISSUE TITLE
The Active Directory connection was not successful.  Please check your settings.

### ISSUE THREAD

**Issue by santana110** [mprahl/ADReset#1]
I at the final stage where I attempt to fill in the LDAPS details. and then I get this error:

The Active Directory connection was not successful.  Please check your settings.

I had use LDP utility and found no problem connecting to the AD.

Is there a way in the ADRESET to see what is going on and why I am unable to connect to AD via LDAPS?

**Comment by InformaticaGuttmann** [comment]
I have the same problen. Did you found the solution?
