### ISSUE TITLE
AD Connection Error

### ISSUE THREAD

**Issue by knightowl1000** [mprahl/ADReset#3]
Hi,

I know you're busy, but I had a question for you in regards to connecting an AD server. I'm running ADReset on a centos box. When trying to connect to the AD server, I get the following error: The Active Directory connection was not successful. Please check your settings.

I checked the error logs, but it has no entries. Do you know a way I can enable debugs to see the exact error to try and tackle that?

Thanks!

**Comment by knightowl1000** [comment]
Solved it! So, it was an issue where I was able to bind via CLI but not via apache.  I stumbled upon this: https://stackoverflow.com/questions/8291631/ldap-works-with-php-cli-but-not-through-apache and it turns out httpd_can_network_connect and httpd_can_connect_ldap were set to off. Changed them to on, restarted the services and I was able to save the connections under local admin!

**Comment by mprahl** [comment]
Nice! Thanks for sharing the solution.
