### ISSUE TITLE
LDAP Search Error

### ISSUE THREAD

**Issue by knightowl1000** [mprahl/ADReset#4]
Hi,

I found another issue. I'm trying to tackle them, but i'm not very strong when it comes to classes and functions. I'm setting up ADReset and when I'm setting up an admin group, I get the following error: 

`[Mon Oct 01 04:32:25.705508 2018] [php7:warn] [pid 13411] [client XXXXXX:50840] PHP Warning:  ldap_search(): Search: Operations error in /var/www/pwreset/resources/classes/AD.php on line 93, referer: http://XXXXXX/settings/systemsettings.php`

Line 93 appears to be grabbing the baseDN and a query. Not sure how they work, any help is greatly appreciated.

Also, I updated the function for mcrypt since it's depreciated and changed it to openssl. Would you want me to do a pull request and have you review it and maybe push it?

**Comment by mprahl** [comment]
Hi @knightowl1000, I'm in the process of rewriting the application in the [ADReset2 repo](https://github.com/mprahl/ADReset2) to have a REST API and SPA frontend.

I appreciate the offer for the PR, but once I'm done with the rewrite, I'll be dropping the PHP version of this.
