### ISSUE TITLE
 AD problem

### ISSUE THREAD

**Issue by Gustavodecker** [mprahl/ADReset#7]
@Good afternoon, with the same error, can you help me, please?

PHP Notice:  Undefined offset: 0 in C:\inetpub\adreset\resources\classes\AD.php on line 432
PHP Warning:  Invalid argument supplied for foreach() in C:\inetpub\adreset\resources\classes\AD.php on line 434
PHP Notice:  Undefined index: dn in C:\inetpub\adreset\resources\classes\AD.php on line 400
PHP Notice:  Undefined index: name in C:\inetpub\adreset\resources\classes\AD.php on line 400

**Comment by mprahl** [comment]
I'm sorry. I recently tried a fresh install on Ubuntu 16.04 with PHP 7, and it works. I haven't recently tried installing this on Windows though.

I'm in the process of rewriting the app in the [ADReset2 repo](https://github.com/mprahl/ADReset2). I'll keep this ticket open though in case someone has a solution.
