### ISSUE TITLE
Problems configuration and doubts

### ISSUE THREAD

**Issue by 96737-3982** [mprahl/ADReset#9]
good afternoon Matt Prahl,

get to perform configure confers procedure in Installing ADReset on Ubuntu 14.04, but now I'm having problems I need to change the language to Portuguese in the pages,
I basically need only some fields that read the AD,
we are thinking of changing the password and confirm and ask the user to change the password information of the AD field.
The ADRESET tool can do this.

**Comment by mprahl** [comment]
Hello,
I don't quite understand your question. Could you try rephrasing it please?
